// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVpaiP9AbnhNxFewNsJPwuy3w4PPjgmDs',
    appId: '1:296784925338:web:34d6fe43cb1fcaa1a34523',
    messagingSenderId: '296784925338',
    projectId: 'fir-api-350f5',
    authDomain: 'fir-api-350f5.firebaseapp.com',
    storageBucket: 'fir-api-350f5.firebasestorage.app',
    measurementId: 'G-1YS7RP991J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCAyTf8Mvy9Nt1QAzMykwLIbiLylPMgf8',
    appId: '1:296784925338:android:44e8dec1056269c9a34523',
    messagingSenderId: '296784925338',
    projectId: 'fir-api-350f5',
    storageBucket: 'fir-api-350f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAutQzTH0BNm32mkrXU38JeGFA1Dksqewc',
    appId: '1:296784925338:ios:fbdf391bbab63d7aa34523',
    messagingSenderId: '296784925338',
    projectId: 'fir-api-350f5',
    storageBucket: 'fir-api-350f5.firebasestorage.app',
    iosClientId: '296784925338-qd5vghmi4flqjo3ma6m4b1qb86bdei9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAutQzTH0BNm32mkrXU38JeGFA1Dksqewc',
    appId: '1:296784925338:ios:fbdf391bbab63d7aa34523',
    messagingSenderId: '296784925338',
    projectId: 'fir-api-350f5',
    storageBucket: 'fir-api-350f5.firebasestorage.app',
    iosClientId: '296784925338-qd5vghmi4flqjo3ma6m4b1qb86bdei9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVpaiP9AbnhNxFewNsJPwuy3w4PPjgmDs',
    appId: '1:296784925338:web:c850054b58ff69cfa34523',
    messagingSenderId: '296784925338',
    projectId: 'fir-api-350f5',
    authDomain: 'fir-api-350f5.firebaseapp.com',
    storageBucket: 'fir-api-350f5.firebasestorage.app',
    measurementId: 'G-6M037KFLWK',
  );

}