// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfKqNmYCGRPsT0jW9Kp_KuIYv5Nlv4RU4',
    appId: '1:818264923499:web:e5c3eb1bcc2df18510802e',
    messagingSenderId: '818264923499',
    projectId: 'fir-demo2-15f3d',
    authDomain: 'fir-demo2-15f3d.firebaseapp.com',
    storageBucket: 'fir-demo2-15f3d.firebasestorage.app',
    measurementId: 'G-JR2L4K65L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClzlJD8I8i4FzfPLVIbCjYXwNB6vO2JNU',
    appId: '1:818264923499:android:de661378c6dbb88b10802e',
    messagingSenderId: '818264923499',
    projectId: 'fir-demo2-15f3d',
    storageBucket: 'fir-demo2-15f3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAotUhyo0IhDJrN03T0e4QpCtLmiCX3jE',
    appId: '1:818264923499:ios:8a169939ff90c12a10802e',
    messagingSenderId: '818264923499',
    projectId: 'fir-demo2-15f3d',
    storageBucket: 'fir-demo2-15f3d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAotUhyo0IhDJrN03T0e4QpCtLmiCX3jE',
    appId: '1:818264923499:ios:8a169939ff90c12a10802e',
    messagingSenderId: '818264923499',
    projectId: 'fir-demo2-15f3d',
    storageBucket: 'fir-demo2-15f3d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfKqNmYCGRPsT0jW9Kp_KuIYv5Nlv4RU4',
    appId: '1:818264923499:web:5605c97b35efa21310802e',
    messagingSenderId: '818264923499',
    projectId: 'fir-demo2-15f3d',
    authDomain: 'fir-demo2-15f3d.firebaseapp.com',
    storageBucket: 'fir-demo2-15f3d.firebasestorage.app',
    measurementId: 'G-XCR43D7Y5Z',
  );
}
