// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIB9jIwdzpsAbLcEGFNyC4fF_cnoBOi78',
    appId: '1:1181949624:web:3a815f2b41845ab7f19e4d',
    messagingSenderId: '1181949624',
    projectId: 'fir-demo-ce0de',
    authDomain: 'fir-demo-ce0de.firebaseapp.com',
    storageBucket: 'fir-demo-ce0de.firebasestorage.app',
    measurementId: 'G-M2S6QL6TYY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaaWm637uAALpZVrXITGZewjgrrAbcOts',
    appId: '1:1181949624:ios:a31ce72d2dc309cdf19e4d',
    messagingSenderId: '1181949624',
    projectId: 'fir-demo-ce0de',
    storageBucket: 'fir-demo-ce0de.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaaWm637uAALpZVrXITGZewjgrrAbcOts',
    appId: '1:1181949624:ios:a31ce72d2dc309cdf19e4d',
    messagingSenderId: '1181949624',
    projectId: 'fir-demo-ce0de',
    storageBucket: 'fir-demo-ce0de.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIB9jIwdzpsAbLcEGFNyC4fF_cnoBOi78',
    appId: '1:1181949624:web:9978138efb918f24f19e4d',
    messagingSenderId: '1181949624',
    projectId: 'fir-demo-ce0de',
    authDomain: 'fir-demo-ce0de.firebaseapp.com',
    storageBucket: 'fir-demo-ce0de.firebasestorage.app',
    measurementId: 'G-LRXG929PMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZuiT5-Cwg6j-Ihq7wcrnRbhs6H22AD20',
    appId: '1:1181949624:android:a4836407c6974382f19e4d',
    messagingSenderId: '1181949624',
    projectId: 'fir-demo-ce0de',
    storageBucket: 'fir-demo-ce0de.firebasestorage.app',
  );

}